---
- name: 'Check if php is installed'
  register: composer_phpcheck
  command: 'php -v | grep -o PHP'
  ignore_errors: true
  changed_when: false

- fail:
    msg: 'PHP needs to be installed before!'
  when: composer_phpcheck | failed

- name: Download composer installer
  get_url:
    url: 'https://getcomposer.org/installer'
    dest: '/tmp/composer-installer.php'

- name: 'Install composer'
  shell: php /tmp/composer-installer.php && mv /tmp/composer.phar /usr/local/bin/composer
  #shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer

- name: 'Set composer chmod'
  file:
    path: /usr/local/bin/composer
    owner: root
    group: root
    mode: 755

- debug:
    var: '{{ composer_selfupdate_minute | default(0) }} - {{ composer_selfupdate_hour | default(21) }} - {{ composer_selfupdate_specialtime | default("daily") }}'

- name: Install self-update cronjob
  cron:
    name: 'Regularly update composer'
    special_time: '{{ composer_selfupdate_specialtime }}'
    job: '/usr/local/bin/composer self-update >> /var/log/composer.log'
    user: root
    state: present
  when: composer_selfupdate