---
- name: 'Check if php is installed'
  register: composer_phpcheck
  command: 'php -v | grep -o PHP'
  ignore_errors: true
  changed_when: false

- name: 'fail when php is not installed'
  fail:
    msg: 'PHP needs to be installed before!'
  when: composer_phpcheck is failed

- name: Download composer installer
  get_url:
    url: 'https://getcomposer.org/installer'
    dest: '/tmp/composer-installer.php'
    mode: 0755

- name: 'Install composer'
  shell: php composer-installer.php && mv composer.phar {{ composer_install_path }}
  args:
    creates: '{{ composer_install_path }}'
    chdir: /tmp

- name: 'Set composer chmod'
  file:
    path: '{{ composer_install_path }}'
    owner: root
    group: root
    mode: 0755

- name: Install self-update cronjob
  cron:
    name: 'Regularly update composer'
    special_time: '{{ composer_selfupdate_specialtime }}'
    job: '{{ composer_install_path }} self-update >> /var/log/composer.log'
    user: root
    state: present
    cron_file: 'composer'
  when: composer_selfupdate